### ISSUE TITLE
spfx react control compatibility

### ISSUE THREAD

**Issue by ganeshkaulkar** [nanddeepn/code-samples#55]
Cannot find module '@pnp/spfx-controls-react/lib/treeView' or its corresponding type declarations.ts(2307)

**Comment by nanddeepn** [comment]
The issue is with PnP Controls, specifically with react-mentions package. Follow the issue on the repo at: https://github.com/pnp/sp-dev-fx-controls-react/issues/1225

Workaround (from the issue thread):
Install the previous version of the 'react-mentions':
npm install react-mentions@4.4.0 --save --save-exact

Install the pnp controls:
npm install @pnp/spfx-controls-react --save --save-exact
